---
title: "Informe"
format: html
---

• 1ª pagina
1. Portada con el nombre asignatura, título del trabajo, autores y fecha de entrega.
2. Descripción del trabajo y contenido.
3. Objeto del trabajo.
• 2º bloque, varias páginas
1. Introducción: condiciones de contorno para el sistema de sensado, acondicionado y
adquisición.
2. Diseño del sistema de sensado y acondicionado de señales.
3. Descripción de la aplicación informática a implementar para la adquisición y procesado.
• 3er bloque, varias páginas
1. Resultados de los ensayos realizados, documentados y comentados.
2. Conclusiones (en una página separada).
• 4º bloque, varias páginas
1. Bibliografía y otra documentación (en una página separada).
2. Anexos


1. Primero, realizar el montaje solamente con un generador controlado, GPIOxx y un LED de carga, esto permite verificar el funcionamiento más rápidamente y realizar las primeras medidas. Ver fotografía en el apartado de resultados.

Los resultados pueden ser similares a los que aparecen en el apartado de resultados y que corresponden a un LED verde. Corresponden las gráficas a las curvas paramétricas de tensión en la carga, en la resistencia y en el LED respecto a la corriente inyectada por la fuente.

```{python}
# Dictionaries for files

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go
import os

data_files = {
    "red": "lab_red.csv",
    "yellow": "lab_yellow.csv",
    "blue": "lab_blue.csv",
    "green": "lab_green.csv",
    "orange": "lab_orange.csv"
}

# plt.figure(figsize=(10, 10))
fig1 = go.Figure()

fig2 = go.Figure()

fig3 = go.Figure()

figVI = go.Figure()


for color in data_files.keys():
    # Load normal data
    df = pd.read_csv(data_files[color])
    df['V_led'] = df['adc34_voltage'] * ((10000+2000)/2000) - df['adc35_voltage']
    df['Iled'] = df['adc35_voltage'] / 100
    df = df[df['Iled'] <= 0.02]
    p_norm = np.poly1d(np.polyfit(df['V_led'], df['Iled'], 4))
    df['fit'] = p_norm(df['V_led'])
    
    # Plot normal
    #plt.plot(df['V_led'], df['dac_value'], label=f"{color} normal", linestyle='--', color=color)
    
    df['V_carga'] = df['adc34_voltage'] * ((10000+2000)/2000)

    # Add traces
    fig1.add_trace(go.Scatter(
        x=df['dac_value'],
        y=df['V_carga'],
        mode='lines',
        name=f'{color} ADC35',
        line=dict(color=color, dash='solid')
    ))

    df['V_R'] = df['adc35_voltage']

    # Add traces
    fig2.add_trace(go.Scatter(
        x=df['dac_value'],
        y=df['V_R'],
        mode='lines',
        name=f'{color} ADC35',
        line=dict(color=color, dash='solid')
    ))

    df['V_R'] = df['adc34_voltage'] * ((10000+2000)/2000) - df['adc35_voltage']

    # Add traces
    fig3.add_trace(go.Scatter(
        x=df['dac_value'],
        y=df['V_led'],
        mode='lines',
        name=f'{color} ADC35',
        line=dict(color=color, dash='solid')
    ))

    figVI.add_trace(go.Scatter(
        x=df['V_led'],
        y=df['Iled']*1000,
        mode='lines',
        name=f'{color} ADC35',
        line=dict(color=color, dash='solid')
    ))

# Layout
fig1.update_layout(
    title="Tension en carga",
    xaxis_title="dac value (bit))",
    yaxis_title="Tension en carga (V)",
    template="plotly_white",
    width=500,
    height=500
)

fig2.update_layout(
    title="Tension en resistencia",
    xaxis_title="V led (V))",
    yaxis_title="I led (mA)",
    template="plotly_white",
    width=500,
    height=500
)

fig3.update_layout(
    title="Tension en LED",
    xaxis_title="V led (V))",
    yaxis_title="I led (mA)",
    template="plotly_white",
    width=500,
    height=500
)

figVI.update_layout(
    title="Corba V-I",
    xaxis_title="V led (V))",
    yaxis_title="I led (mA)",
    template="plotly_white",
    width=500,
    height=500
)

fig1.show()

fig2.show()

fig3.show()

figVI.show()

```

2. Obtener tensiones de polarización en directa reales de los distintos LED con 1 mA, 10 mA y 20 mA, indicarlos en forma de tabla y compararlos con los datos del fabricante.


3. Representar en una gráfica las curvas corriente-tensión de los distintos LED ensayados.